<?php
define("DB_SERVER","localhost");
define("DB_NAME","ebook");
define("DB_USER","root");
define("DB_PASS","giveMePass");
define("SERVER_URL","http://localhost/viewer");
define("errorurl","http://localhost/viewer/index.html");
define("saveurl","http://localhost/viewer/index.html");
define("successurl","http://localhost/viewer/read.html");
define("pdfDirectory","../pdf/");
define("thumbDirectory","../pdfimage/");
?>
