<?php
    define("DB_SERVER","localhost");
    define("DB_NAME","shaodb");
    define("DB_USER","shaohuan");
    define("DB_PASS","shaohuan");
    define("PEAR_PATH","/usr/share/pear");
    define("SERVER_PATH","/shao");
    define("SERVER_URL","https://dbgpu.d1.comp.nus.edu.sg/shao");
    define("DATASERVER_URL","http://dbgpu.d1.comp.nus.edu.sg/shao");
    define("errorurl","https://dbgpu.d1.comp.nus.edu.sg/shao/index.html");
    define("saveurl","https://dbgpu.d1.comp.nus.edu.sg/shao/index.html");
    define("successurl","https://dbgpu.d1.comp.nus.edu.sg/shao/read.html");
    define("pdfDirectory","/var/www/httpdocs/shao/pdf/");
    define("thumbDirectory","/var/www/httpdocs/shao/pdfimage/");
?>
