<?php
define("DB_SERVER","localhost");
define("DB_NAME","ebook");
define("DB_USER","root");
define("DB_PASS","giveMePass");
define("SERVER_URL","http://www.yunreading.com/viewer");
define("errorurl","http://www.yunreading.com/index.html");
define("saveurl","http://www.yunreading.com/index.html");
define("successurl","http://www.yunreading.com/viewer/read.html");
define("pdfDirectory","../pdf/");
define("thumbDirectory","../pdfimage/");
define("DATASERVER_URL","http://www.yunreading.com/viewer");
?>
