<?php
    define("DB_SERVER","localhost");
    define("DB_NAME","annot");
    define("DB_USER","root");
    define("DB_PASS","giveMePass");
    define("PEAR_PATH","/usr/local/share/pear");
    define("SERVER_PATH","/viewer");
    define("SERVER_URL","http://localhost/viewer");
    define("DATASERVER_URL","http://localhost/viewer");
    define("errorurl","http://localhost/viewer/index.html");
    define("saveurl","http://localhost/viewer/index.html");
    define("successurl","http://localhost/viewer/read.html");
    define("pdfDirectory","../pdf/");
    define("thumbDirectory","../pdfimage/");
?>
